name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v4
     - name: checkout 
       run: git submodule update --init --recursive
     - name: build
       run: ./build.bat
       shell: cmd
